title: MyBookName
author:
- Your Name here
subtitle: Give yourself a subtitle
abstract: Abstact text
keywords: 
- Add
- Some
- Keywords
- Here
subject: Subject of book 
description: Put a description here
category: Category of book 

